/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _KWS_Result_Prediction {
    char label[33];
    float value;
} KWS_Result_Prediction;

typedef struct _KWS_Result_Timing {
    int32_t dsp;
    float classification;
} KWS_Result_Timing;

typedef struct _KWS_Result {
    KWS_Result_Timing timing;
    pb_size_t predictions_count;
    KWS_Result_Prediction predictions[3];
} KWS_Result;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define KWS_Result_init_default                  {KWS_Result_Timing_init_default, 0, {KWS_Result_Prediction_init_default, KWS_Result_Prediction_init_default, KWS_Result_Prediction_init_default}}
#define KWS_Result_Prediction_init_default       {"", 0}
#define KWS_Result_Timing_init_default           {0, 0}
#define KWS_Result_init_zero                     {KWS_Result_Timing_init_zero, 0, {KWS_Result_Prediction_init_zero, KWS_Result_Prediction_init_zero, KWS_Result_Prediction_init_zero}}
#define KWS_Result_Prediction_init_zero          {"", 0}
#define KWS_Result_Timing_init_zero              {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define KWS_Result_Prediction_label_tag          1
#define KWS_Result_Prediction_value_tag          2
#define KWS_Result_Timing_dsp_tag                1
#define KWS_Result_Timing_classification_tag     2
#define KWS_Result_timing_tag                    1
#define KWS_Result_predictions_tag               2

/* Struct field encoding specification for nanopb */
#define KWS_Result_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  timing,            1) \
X(a, STATIC,   REPEATED, MESSAGE,  predictions,       2)
#define KWS_Result_CALLBACK NULL
#define KWS_Result_DEFAULT NULL
#define KWS_Result_timing_MSGTYPE KWS_Result_Timing
#define KWS_Result_predictions_MSGTYPE KWS_Result_Prediction

#define KWS_Result_Prediction_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   label,             1) \
X(a, STATIC,   REQUIRED, FLOAT,    value,             2)
#define KWS_Result_Prediction_CALLBACK NULL
#define KWS_Result_Prediction_DEFAULT NULL

#define KWS_Result_Timing_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    dsp,               1) \
X(a, STATIC,   REQUIRED, FLOAT,    classification,    2)
#define KWS_Result_Timing_CALLBACK NULL
#define KWS_Result_Timing_DEFAULT NULL

extern const pb_msgdesc_t KWS_Result_msg;
extern const pb_msgdesc_t KWS_Result_Prediction_msg;
extern const pb_msgdesc_t KWS_Result_Timing_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define KWS_Result_fields &KWS_Result_msg
#define KWS_Result_Prediction_fields &KWS_Result_Prediction_msg
#define KWS_Result_Timing_fields &KWS_Result_Timing_msg

/* Maximum encoded size of messages (where known) */
#define KWS_Result_Prediction_size               39
#define KWS_Result_Timing_size                   16
#define KWS_Result_size                          141
#define MESSAGE_PB_H_MAX_SIZE                    KWS_Result_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
