# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\"\xb8\x01\n\nKWS_Result\x12\"\n\x06timing\x18\x01 \x02(\x0b\x32\x12.KWS_Result.Timing\x12+\n\x0bpredictions\x18\x02 \x03(\x0b\x32\x16.KWS_Result.Prediction\x1a*\n\nPrediction\x12\r\n\x05label\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x02\x1a-\n\x06Timing\x12\x0b\n\x03\x64sp\x18\x01 \x02(\x05\x12\x16\n\x0e\x63lassification\x18\x02 \x02(\x02'
)




_KWS_RESULT_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='KWS_Result.Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='KWS_Result.Prediction.label', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='KWS_Result.Prediction.value', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=155,
)

_KWS_RESULT_TIMING = _descriptor.Descriptor(
  name='Timing',
  full_name='KWS_Result.Timing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dsp', full_name='KWS_Result.Timing.dsp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classification', full_name='KWS_Result.Timing.classification', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=202,
)

_KWS_RESULT = _descriptor.Descriptor(
  name='KWS_Result',
  full_name='KWS_Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timing', full_name='KWS_Result.timing', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predictions', full_name='KWS_Result.predictions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_KWS_RESULT_PREDICTION, _KWS_RESULT_TIMING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=202,
)

_KWS_RESULT_PREDICTION.containing_type = _KWS_RESULT
_KWS_RESULT_TIMING.containing_type = _KWS_RESULT
_KWS_RESULT.fields_by_name['timing'].message_type = _KWS_RESULT_TIMING
_KWS_RESULT.fields_by_name['predictions'].message_type = _KWS_RESULT_PREDICTION
DESCRIPTOR.message_types_by_name['KWS_Result'] = _KWS_RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KWS_Result = _reflection.GeneratedProtocolMessageType('KWS_Result', (_message.Message,), {

  'Prediction' : _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), {
    'DESCRIPTOR' : _KWS_RESULT_PREDICTION,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:KWS_Result.Prediction)
    })
  ,

  'Timing' : _reflection.GeneratedProtocolMessageType('Timing', (_message.Message,), {
    'DESCRIPTOR' : _KWS_RESULT_TIMING,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:KWS_Result.Timing)
    })
  ,
  'DESCRIPTOR' : _KWS_RESULT,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:KWS_Result)
  })
_sym_db.RegisterMessage(KWS_Result)
_sym_db.RegisterMessage(KWS_Result.Prediction)
_sym_db.RegisterMessage(KWS_Result.Timing)


# @@protoc_insertion_point(module_scope)
