# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\"t\n\x05\x42oard\x12\x18\n\x04rows\x18\x01 \x03(\x0b\x32\n.Board.Row\x1a!\n\x03Row\x12\x1a\n\x05marks\x18\x01 \x03(\x0e\x32\x0b.Board.Mark\".\n\x04Mark\x12\x0e\n\nMARK_EMPTY\x10\x00\x12\n\n\x06MARK_X\x10\x01\x12\n\n\x06MARK_O\x10\x02'
)



_BOARD_MARK = _descriptor.EnumDescriptor(
  name='Mark',
  full_name='Board.Mark',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MARK_EMPTY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARK_X', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARK_O', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=87,
  serialized_end=133,
)
_sym_db.RegisterEnumDescriptor(_BOARD_MARK)


_BOARD_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='Board.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='marks', full_name='Board.Row.marks', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=85,
)

_BOARD = _descriptor.Descriptor(
  name='Board',
  full_name='Board',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='Board.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BOARD_ROW, ],
  enum_types=[
    _BOARD_MARK,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=133,
)

_BOARD_ROW.fields_by_name['marks'].enum_type = _BOARD_MARK
_BOARD_ROW.containing_type = _BOARD
_BOARD.fields_by_name['rows'].message_type = _BOARD_ROW
_BOARD_MARK.containing_type = _BOARD
DESCRIPTOR.message_types_by_name['Board'] = _BOARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Board = _reflection.GeneratedProtocolMessageType('Board', (_message.Message,), {

  'Row' : _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), {
    'DESCRIPTOR' : _BOARD_ROW,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:Board.Row)
    })
  ,
  'DESCRIPTOR' : _BOARD,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Board)
  })
_sym_db.RegisterMessage(Board)
_sym_db.RegisterMessage(Board.Row)


# @@protoc_insertion_point(module_scope)
